/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getBaseband.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(25f39f08051274e3f34713b1fbbe6466)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getBaseband.h>
// pydoc.h is automatically generated in the build directory
#include <getBaseband_pydoc.h>

void bind_getBaseband(py::module& m)
{

    using getBaseband    = gr::customModule::getBaseband;


    py::class_<getBaseband, gr::block, gr::basic_block,
        std::shared_ptr<getBaseband>>(m, "getBaseband", D(getBaseband))

        .def(py::init(&getBaseband::make),
           py::arg("fft_len"),
           py::arg("baseband_filename"),
           D(getBaseband,make)
        )
        



        ;




}








