/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getCFO.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c65d9433104f9497b1ff21031e83fd46)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getCFO.h>
// pydoc.h is automatically generated in the build directory
#include <getCFO_pydoc.h>

void bind_getCFO(py::module& m)
{

    using getCFO    = gr::customModule::getCFO;


    py::class_<getCFO, gr::block, gr::basic_block,
        std::shared_ptr<getCFO>>(m, "getCFO", D(getCFO))

        .def(py::init(&getCFO::make),
           py::arg("sensitivity"),
           py::arg("freq_offsets_filename"),
           D(getCFO,make)
        )
        



        ;




}








