/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getEqlizedsig.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd34cdecc39a702639dbaf97896f12a6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getEqlizedsig.h>
// pydoc.h is automatically generated in the build directory
#include <getEqlizedsig_pydoc.h>

void bind_getEqlizedsig(py::module& m)
{

    using getEqlizedsig    = gr::customModule::getEqlizedsig;


    py::class_<getEqlizedsig, gr::block, gr::basic_block,
        std::shared_ptr<getEqlizedsig>>(m, "getEqlizedsig", D(getEqlizedsig))

        .def(py::init(&getEqlizedsig::make),
           py::arg("equalizer"),
           py::arg("equlizedsig_filename"),
           py::arg("fft_len"),
           py::arg("cp_len"),
           py::arg("tsb_key"),
           D(getEqlizedsig,make)
        )
        



        ;




}








