/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getEqsignal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4b2a3a4be57790333ba853115fb85df1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getEqsignal.h>
// pydoc.h is automatically generated in the build directory
#include <getEqsignal_pydoc.h>

void bind_getEqsignal(py::module& m)
{

    using getEqsignal    = gr::customModule::getEqsignal;


    py::class_<getEqsignal, gr::block, gr::basic_block,
        std::shared_ptr<getEqsignal>>(m, "getEqsignal", D(getEqsignal))

        .def(py::init(&getEqsignal::make),
           py::arg("fft_len"),
           py::arg("eqsignal_filename"),
           D(getEqsignal,make)
        )
        



        ;




}








