/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getPayload.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e2563c586b3ed5152d556e792107dede)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getPayload.h>
// pydoc.h is automatically generated in the build directory
#include <getPayload_pydoc.h>

void bind_getPayload(py::module& m)
{

    using getPayload    = gr::customModule::getPayload;


    py::class_<getPayload, gr::block, gr::basic_block,
        std::shared_ptr<getPayload>>(m, "getPayload", D(getPayload))

        .def(py::init(&getPayload::make),
           py::arg("fft_len"),
           py::arg("payload_filename"),
           D(getPayload,make)
        )
        



        ;




}








