/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getSignal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0aee507cb728b1be1072f38c9b9e6fc8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getSignal.h>
// pydoc.h is automatically generated in the build directory
#include <getSignal_pydoc.h>

void bind_getSignal(py::module& m)
{

    using getSignal    = gr::customModule::getSignal;


    py::class_<getSignal, gr::block, gr::basic_block,
        std::shared_ptr<getSignal>>(m, "getSignal", D(getSignal))

        .def(py::init(&getSignal::make),
           py::arg("item_size"),
           py::arg("signal_filename"),
           D(getSignal,make)
        )
        



        ;




}








