/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getSyncsymbol.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fb88022fb8d0dd9da1597a978fb2f39c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getSyncsymbol.h>
// pydoc.h is automatically generated in the build directory
#include <getSyncsymbol_pydoc.h>

void bind_getSyncsymbol(py::module& m)
{

    using getSyncsymbol    = gr::customModule::getSyncsymbol;


    py::class_<getSyncsymbol, gr::block, gr::basic_block,
        std::shared_ptr<getSyncsymbol>>(m, "getSyncsymbol", D(getSyncsymbol))

        .def(py::init(&getSyncsymbol::make),
           py::arg("sync_symbol1"),
           py::arg("sync_symbol2"),
           py::arg("n_data_symbols"),
           py::arg("max_carr_offset"),
           py::arg("force_one_sync_symbol"),
           py::arg("sync_filename1"),
           py::arg("sync_filename2"),
           py::arg("fine_cfo_filename"),
           D(getSyncsymbol,make)
        )
        



        ;




}








