/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(getTaps.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(acf114272e540da394b7ad2c5c637820)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/getTaps.h>
// pydoc.h is automatically generated in the build directory
#include <getTaps_pydoc.h>

void bind_getTaps(py::module& m)
{

    using getTaps = gr::customModule::getTaps;


    py::class_<getTaps, gr::block, gr::basic_block, std::shared_ptr<getTaps>>(
        m, "getTaps", D(getTaps))

        .def(py::init(&getTaps::make),
             py::arg("fft_len"),
             py::arg("cp_len"),
             py::arg("propagate_channel_state"),
             py::arg("fixed_frame_len"),
             py::arg("channel_taps_filename"),
             py::arg("carrier_offsets_filename"),
             D(getTaps, make))


        ;
}
