/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(recordBaseband.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f0379db54c80b6ad1ce655429cb05ec0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/recordBaseband.h>
// pydoc.h is automatically generated in the build directory
#include <recordBaseband_pydoc.h>

void bind_recordBaseband(py::module& m)
{

    using recordBaseband    = gr::customModule::recordBaseband;


    py::class_<recordBaseband, gr::block, gr::basic_block,
        std::shared_ptr<recordBaseband>>(m, "recordBaseband", D(recordBaseband))

        .def(py::init(&recordBaseband::make),
           py::arg("header_len"),
           py::arg("items_per_symbol"),
           py::arg("guard_interval"),
           py::arg("length_tag_key"),
           py::arg("trigger_tag_key"),
           py::arg("output_symbols"),
           py::arg("itemsize"),
           py::arg("cfo_itemsize"),
           py::arg("timing_tag_key"),
           py::arg("samp_rate"),
           py::arg("special_tags"),
           py::arg("header_padding"),
           py::arg("payload_filename"),
           py::arg("cfo_filename"),
           py::arg("rawiq_filename"),
           D(recordBaseband,make)
        )
        



        ;




}








