/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Serlizsig.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5cff1be7dd28e9f365fe16d3e192aedd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <customModule/Serlizsig.h>
// pydoc.h is automatically generated in the build directory
#include <Serlizsig_pydoc.h>

void bind_Serlizsig(py::module& m)
{

    using Serlizsig    = gr::customModule::Serlizsig;


    py::class_<Serlizsig, gr::block, gr::basic_block,
        std::shared_ptr<Serlizsig>>(m, "Serlizsig", D(Serlizsig))

        .def(py::init(&Serlizsig::make),
           py::arg("fft_len"),
           py::arg("occupied_carriers"),
           py::arg("len_tag_key"),
           py::arg("packet_len_tag_key"),
           py::arg("symbols_skipped"),
           py::arg("carr_offset_key"),
           py::arg("input_is_shifted"),
           py::arg("signal_filename"),
           py::arg("channel_taps_filename"),
           D(Serlizsig,make)
        )
        



        ;




}








